### ISSUE TITLE
psk-barcode-scanner failed to start

### ISSUE THREAD

**Issue by Mastaleru** [webcardinal/cardinal-barcode#3]
ErrorStack:
![image](https://user-images.githubusercontent.com/1469129/145862023-03176beb-bcf2-49ee-a121-5246208d10a2.png)

Usages: https://github.com/PharmaLedger-IMI/csc-workspace-main/blob/master/csc-cmo-ssapp/code/pages/scan-shipment.html#L35

**Comment by denypatrascu** [comment]
This is currently in progress.

Reason for the error: When canvas is not in viewport `getImageData` throws the above error.
